config/routes.rb
Rails.application.routes.draw do
 

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   
  resources :users, only: [:new, :create]
   get 'login', to: 'sessions#new'
   post 'login', to: 'sessions#create'
   get 'welcome', to: 'sessions#welcome'
   get 'authorized', to: 'sessions#page_requires_login'
   
   
      delete '/logout' => 'sessions#destroy'
  
    


  root "products#index"
     resources :products do
     resources :comments
  end

  resources :shops

  resources :carts do
      post 'add_to_cart/:product_id', to: 'carts#add_to_cart', as: 'add_to_cart'
  end

  resources :likes, only:[:create,:destroy]





end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :shops, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_one_attached :image, dependent: :destroy
  
  has_many :comments, :as => :commentable, dependent: :destroy
  has_many :shops, dependent: :destroy

  
  has_many :likes, dependent: :destroy

end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  
  
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  validates :username, presence: true
  validates :password, length: { minimum: 6 }

  has_many :likes, dependent: :destroy

  has_one :cart, dependent: :destroy

  has_many :products, dependent: :destroy
  has_many :comments, :as => :commentable, dependent: :destroy


  after_create :initialize_cart

  def initialize_cart
    Cart.create(user_id:id )
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authorized
	helper_method :current_user
	helper_method :logged_in?
	
	def current_user    
	    User.find_by(id: session[:user_id])  
	end
	
	def logged_in?
	       
	    !current_user.nil?  
	end

	def authorized
         redirect_to '/welcome' unless logged_in?
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  
  def add_to_cart
        product = Product.find(params[:product_id])
        cart = current_user.cart
        shops = cart.shops
        item = shops.find_by(product_id: product.id)
        if item
  	      item.save
        else
  	      shops.create(product_id: product.id)
        end
    redirect_to root_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 
  def show
  end
  
  def create
    @product = Product.find(params[:product_id])
    @comment = @product.comments.create(comment_params)
    redirect_to product_path(@product)
  end

  def destroy
    @product = Product.find params[:product_id]
    @comment = @product.comments.find(params[:id])
    @comment.destroy
    redirect_to product_comment_path(@product)
  end


  private
  def comment_params
    params.require(:comment).permit(:body, :user_id, :product_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	def create
		 @like = current_user.likes.new(like_params)
		 if !@like.save
		   flash[:notice] = @like.errors.full_message.to_sentence
		 end
		   redirect_to @like.product
	end

	def destroy
		 @like = current_user.likes.find(params[:id])
		 product = @like.product
		 @like.destroy
		 redirect_to product
	end


	 private

    def like_params
	    params.require(:like).permit(:product_id)
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		@products = Product.all
	end

	def show
        @product = Product.find(params[:id])
    end

	def new
		@product = current_user.products.build
	end

	def create
		@product = current_user.products.build(product_params)
		if @product.save
			redirect_to @product
		else
			render :new, status: :unprocessable_entity
		end
	end

	def edit
		@product = current_user.products.find(params[:id])
	end

	def update
		@product = current_user.products.find(params[:id])
		if @product.update(product_params)
			redirect_to @product
		else
			render :edit, status: :unprocessable_entity
		end
	end 

	def destroy
	    @product = current_user.products.find(params[:id])
	    @product = current_user.products.find(params[:id])
	    @product.destroy
	    redirect_to root_path, status: :see_other
    end

	private

	def product_params
		params.require(:product).permit(:name, :price, :description, :image )
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :welcome]

  def new
  end
  
  def create
     @user = User.find_by(username: params[:username])
     if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to '/products'
     else
        redirect_to '/welcome'
     end
  end

  def page_requires_login
  end

  def login
  end

  def welcome
  end

  def destroy
    session[:user_id]=nil
    redirect_to'/login'
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
	def index
	    @shops = Shop.all
	end

  def show
      @shop = current_shop
     
  end

 	def destroy
	    @shop = Shop.find(params[:id])
	    @shop.destroy
	    redirect_to @shop
  end

	
  private

	def shop_params
		params.require(:shop).permit( :product_id)
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def new
     @user = User.new
  end

  def create
     @user = User.create(params.require(:user).permit(:username, :password, :role))
     session[:user_id] = @user.id
     redirect_to '/login'
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<h2>Add a comment:</h2>
<%= form_with model: [ @product, @product.comments.build ] do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/products/_comment_form.html.erb
 <!--Comments-->
<div class="card container shadow p-3 mb-5 bg-white rounded">    
    <div class="card-body"> 
       <h3>Comment Plz:</h3>
            <%= form_with model: [ @product, @product.comments.build ] do |form| %>
             
               <p>
                   <%= form.label :body %><br>
                   <%= form.text_area :body %>
               </p>
               <p>
                   <%= form.submit %>
               </p>
            <% end %>
    </div>
</div>

app/views/products/_comment_show.html.erb
 
<div class="card container shadow p-3 mb-0 bg-white rounded">    
   <div class="card-body"> 
       <h3>Comments</h3>
      <% @product.comments.each do |comment| %>
         <p>
             <strong>Plz Comment:</strong>
             <%= comment.body %>     
             <%= link_to "Delete Comment", product_comment_path(@product, comment), data: {
                         turbo_method: :delete,
                         turbo_confirm: "Are you sure?"
                       } %>
         </p> 
      <% end %>
   </div>
</div>

app/views/products/_form.html.erb
 <h3> <%= link_to "Back", products_path(@user), class:"btn btn-outline-primary" %></h3>
<%= form_with model: product  do |form| %>

	<div>
		<%= form.label :name %><br>
		<%= form.text_field :name %> 
		<% product.errors.full_messages_for(:name).each do |message| %>
		<div><%= message %></div>
		<% end %>
	</div>
	<div>
		<%= form.label :price %><br>
		<%= form.text_area :price %><br>
		<% product.errors.full_messages_for(:price).each do |message| %>
		<div><%= message %></div>
		<% end %>
	</div>  
	<div>
		<%= form.label :description %><br>
		<%= form.text_area :description %><br>
		<% product.errors.full_messages_for(:description).each do |message| %>
		<div><%= message %></div>
		<% end %>
	</div>  
	<div>	
	     <%= form.file_field :image %>
	</div>
	<div>
		<%= form.submit %>
	</div>

<% end %>

app/views/products/_like_show.html.erb
<!--likes-->
<div class="card container shadow p-3 mb-0 bg-white rounded">    
     <div class="card-body"> <br>
          <strong>Plz Like This Product :</strong>
       <%= @product.likes.count %> 
            <% like = current_user.likes.find_by(product: @product) %>
            <% if like.nil? %>
               <%= button_to "like", likes_path, params: {like: {product_id: @product.id }}, method: :post %>
            <% else %>
               <%= button_to "UnLike", like_path(like), method: :delete %>
       <% end %>
     </div>
</div>

app/views/products/edit.html.erb
<h1>Edit Products</h1>


<%= render "form", product: @product %>

app/views/products/index.html.erb
<h3>All Products <hr></h3>
<div class="table-responsive-lg">
    <table class="table">
            <tr>
                  <th>Image</th>
                  <th>Name</th>
                  <th>Price</th>
                  <th>User</th>
            </tr> 
            <tr>
                <% @products.each do |product| %>
                    <td> <%= image_tag product.image, size:122 if product.image.attached? %></td> 
                    <td><%=  product.name %></td>
                    <td><%=  product.price %></td>
                    <td><%= product.user.username %></td>

                        <td><%= link_to "show", product, class:"btn btn-success" %>
                    
                        <td> <%= button_to 'Add to cart',  cart_add_to_cart_path(product_id: product.id, cart_id: current_user.cart.id), :method => :post, remote: true, class:"btn btn-success" %></td>
                       
            </tr>    
                <% end %>
   </table>
</div>
<% if current_user.role == "seller" %>
<br> <center> <%= link_to "New Product", new_product_path,class:"btn btn-primary"  %></center>
  <% end %>

app/views/products/new.html.erb
<h3>New Product</h3>

<%= render "form", product: @product %>

app/views/products/show.html.erb
    <%= link_to "Back", products_path(@user), class:"btn btn-outline-primary" %><br>
<strong>Product Details</strong>   
<div class="card container shadow  mb-0 bg-white rounded">    
    <div class="card-body"> 
        <div class="text-center">
       
           <%= image_tag @product.image, style: "width:150px;height:150px;", class: "card-img-top rounded-lg border border-dark m-2 "%>
            <p> 
               <strong>Product Name:</strong>
               <%= @product. name %>
            </p>

            <p>
               <strong>Product Price:</strong>
               <%= @product.price %>
            </p>

            <p>
               <strong>User Name:</strong>
                <%= @product.user.username %>
            </p>
          
            <p>
               <strong>Product Description:</strong>
               <%= @product.description %>
            </p>
        
        
            <% if @product.user == current_user %>
                <%= link_to "Destroy", product_path(@product), 
                       data: { 
                                  turbo_method: :delete, 
                                  turbo_confirm: "Are you sure?"
                             } , class:"btn btn-success" %>
            
                <%= link_to 'Edit', edit_product_path(@product),  class:"btn btn-success" %> &nbsp;
                <%= link_to 'Back', root_path ,  class:"btn btn-success" %>
            <% end%>
            </div>
    </div>
</div>
 <!--likes-->
 
<%= render partial: "like_show", locals: {like: @like} %>

 <!--Comments-->

<%= render partial: "comment_show", locals: {comment: @comment} %>


<%= render :partial => "comment_form"%>

app/views/shops/index.html.erb
     <%= link_to "Back", products_path(@user), class:"btn btn-outline-primary" %>
     <h3> Product details<hr> </h3>
<div class="table-responsive-lg">
<table class="table">
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th>User</th>

    </tr> 
    <tr>
      <% current_user.cart.shops.each do |shop| %>
            <td> <%= image_tag shop.product.image, size:122%></td> 
            <td><%=  shop.product.name %></td>
            <td><%=  shop.product.price %></td>
            <td><%= shop.product.description %></td>
            <td><%= shop.product.user.username %></td>
            <td><%= link_to "Remove",shop_path(shop) , data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  }  ,class:"btn btn-success" %></td>

           
       </tr>
      <% end %>
   
</table></div>
 

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f|%>
  <%= f.label :username%><br>
  <%= f.text_field :username%><br><br>

 <%= f.select:role, ["seller","buyer"] %>

    <%= f.label :password%><br>
  <%= f.password_field :password%><br><br>
  <%= f.submit %>
<%end%>