config/routes.rb
Rails.application.routes.draw do
 

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   
  resources :users, only: [:new, :create]
   get 'login', to: 'sessions#new'
   post 'login', to: 'sessions#create'
   get 'welcome', to: 'sessions#welcome'
   get 'authorized', to: 'sessions#page_requires_login'
   
   
      delete '/logout' => 'sessions#destroy'
  
    


  root "products#index"
     resources :products do
     resources :comments
  end

  resources :shops

  resources :carts do
      post 'add_to_cart/:product_id', to: 'carts#add_to_cart', as: 'add_to_cart'
  end

  resources :likes, only:[:create,:destroy]





end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :shops, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_one_attached :image, dependent: :destroy
  
  has_many :comments, :as => :commentable, dependent: :destroy
  has_many :shops, dependent: :destroy

  
  has_many :likes, dependent: :destroy

end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  
  
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  validates :username, presence: true
  validates :password, length: { minimum: 6 }

  has_many :likes, dependent: :destroy

  has_one :cart, dependent: :destroy

  has_many :products, dependent: :destroy
  has_many :comments, :as => :commentable, dependent: :destroy


  after_create :initialize_cart

  def initialize_cart
    Cart.create(user_id:id )
  end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  
  def add_to_cart
        product = Product.find(params[:product_id])
        cart = current_user.cart
        shops = cart.shops
        item = shops.find_by(product_id: product.id)
        if item
  	      item.save
        else
  	      shops.create(product_id: product.id)
        end
    redirect_to root_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 
  def show
  end
  
  def create
    @product = Product.find(params[:product_id])
    @comment = @product.comments.create(comment_params)
    redirect_to product_path(@product)
  end

  def destroy
    @product = Product.find params[:product_id]
    @comment = @product.comments.find(params[:id])
    @comment.destroy
    redirect_to product_comment_path(@product)
  end


  private
  def comment_params
    params.require(:comment).permit(:body, :user_id, :product_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	def create
		 @like = current_user.likes.new(like_params)
		 if !@like.save
		   flash[:notice] = @like.errors.full_message.to_sentence
		 end
		   redirect_to @like.product
	end

	def destroy
		 @like = current_user.likes.find(params[:id])
		 product = @like.product
		 @like.destroy
		 redirect_to product
	end


	 private

    def like_params
	    params.require(:like).permit(:product_id)
	end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
	def index
	    @shops = Shop.all
	end

  def show
      @shop = current_shop
     
  end

 	def destroy
	    @shop = Shop.find(params[:id])
	    @shop.destroy
	    redirect_to @shop
  end

	
  private

	def shop_params
		params.require(:shop).permit( :product_id)
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def new
     @user = User.new
  end

  def create
     @user = User.create(params.require(:user).permit(:username, :password, :role))
     session[:user_id] = @user.id
     redirect_to '/login'
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SessionPractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="  sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
    </script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <style>
      .photo-row { text-align: right; }

    </style>

  </head>

  <body>

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                  <%= image_tag "olx.png", height: 50 %>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <% if logged_in? %>
                       <h5>Welcome, <%= current_user.username %></h5>&nbsp;&nbsp;
                    <%end%>
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                      <% if current_user.present? %>
                           <li class="btn btn-primary" ><%= button_to "Log Out", logout_path, method: :delete%></li>        
                      <% else %>
                            <li  class="btn btn-primary"><%= button_to "Sign Up", '/users/new', method: :get %></li>&nbsp;&nbsp;
                            <li  class="btn btn-primary"><%= button_to "Login", '/login', method: :get %></li>   
                       <% end %> 
                    </ul>
                    <form class="d-flex">
                       <% if current_user.present? %>
                          <%= link_to "Cart", shops_path,class:"btn btn-primary" %>
                       <% end %> 
                    </form>
                  </div>
                </div>
             </nav>
      <div class="container">

            <%= yield %>
            
      </div>

            <footer class="page-footer font-small blue">
                <div  class="font-weight-bold text-uppercase mt-3  text-center" style= "background-color: deepskyblue;">
                  Created By @PawanShendge 
                  <div class="photo-row"><%= image_tag "p.png", height: 70 %></div>
                  </div>
                </div>
            </footer>
      
  </body>


</html>